import fs from 'node:fs';
import path from 'node:path';
import { StorageError } from './path-manager.js';

// ─── Backup filename contract ────────────────────────────────────────────
//
// Filenames are always generated by the application (never accepted from a
// caller) so that listing/restore can trust the managed backup directory
// without re-validating arbitrary user input. Format:
//
//   creatorcrate-<UTC timestamp>.sqlite
//   creatorcrate-2026-07-29T192447Z.sqlite
//
// The timestamp is filesystem-safe (no colons) and sorts lexicographically
// in creation order.

const BACKUP_PREFIX = 'creatorcrate-';
const BACKUP_EXT = '.sqlite';
const BACKUP_FILENAME_RE = /^creatorcrate-\d{4}-\d{2}-\d{2}T\d{6}Z(-\d+)?\.sqlite$/;

/**
 * Format the current (or supplied) time as a filesystem-safe UTC timestamp,
 * e.g. "2026-07-29T192447Z".
 *
 * @param {Date} [date]
 * @returns {string}
 */
export function formatBackupTimestamp(date = new Date()) {
  const iso = date.toISOString(); // 2026-07-29T19:24:47.123Z
  const [datePart, timePart] = iso.split('T');
  const time = timePart.slice(0, 8).replace(/:/g, ''); // 192447
  return `${datePart}T${time}Z`;
}

/**
 * Generate a collision-safe backup filename for the given directory.
 * Appends "-1", "-2", ... if the base timestamped name is already taken
 * (e.g. two backups requested within the same second).
 *
 * @param {string} backupDir - Resolved, existing backup directory
 * @param {Date} [date]
 * @returns {string} filename only (no directory component)
 */
export function generateBackupFilename(backupDir, date = new Date()) {
  const timestamp = formatBackupTimestamp(date);
  const base = `${BACKUP_PREFIX}${timestamp}${BACKUP_EXT}`;

  if (!fs.existsSync(path.join(backupDir, base))) {
    return base;
  }

  let n = 1;
  while (true) {
    const candidate = `${BACKUP_PREFIX}${timestamp}-${n}${BACKUP_EXT}`;
    if (!fs.existsSync(path.join(backupDir, candidate))) {
      return candidate;
    }
    n += 1;
  }
}

/**
 * True if `name` matches the application-generated backup filename shape.
 * Used by listing/restore to ignore staging, rollback, and unrelated files.
 *
 * @param {string} name
 * @returns {boolean}
 */
export function isManagedBackupFilename(name) {
  return BACKUP_FILENAME_RE.test(name);
}

// ─── Containment + symlink checks (mirrors project-storage.js) ──────────

function isContained(root, target) {
  const relative = path.relative(root, target);
  return relative !== '' && !relative.startsWith('..') && !path.isAbsolute(relative);
}

/**
 * Walk each existing path component from root to target; refuse any symlink.
 *
 * @param {string} root - Normalized absolute root path
 * @param {string} target - Normalized absolute target path
 * @throws {StorageError} if any existing component is a symbolic link
 */
function checkSymlinks(root, target) {
  const relative = path.relative(root, target);
  if (relative === '') return;

  const parts = relative.split(path.sep);
  let current = root;

  for (const part of parts) {
    current = path.join(current, part);
    try {
      const stats = fs.lstatSync(current);
      if (stats.isSymbolicLink()) {
        throw new StorageError(
          `Backup path contains a symbolic link at "${path.basename(current)}".`
        );
      }
    } catch (err) {
      if (err instanceof StorageError) throw err;
      if (err.code === 'ENOENT') return; // Non-existent segment → further can't be vectors
      throw new StorageError(`Cannot access path component "${path.basename(current)}".`);
    }
  }
}

/**
 * Resolve the managed backup directory beneath APP_DATA_ROOT and ensure it
 * exists with safe permissions (owner-only read/write/execute). Refuses to
 * follow a symlinked backup directory.
 *
 * @param {string} appDataRoot - Absolute, resolved APP_DATA_ROOT
 * @returns {string} Resolved, existing absolute path to the backup directory
 * @throws {StorageError}
 */
export function resolveBackupDir(appDataRoot) {
  const normalizedRoot = path.resolve(appDataRoot);
  const backupDir = path.resolve(normalizedRoot, 'backups');

  if (!isContained(normalizedRoot, backupDir)) {
    throw new StorageError('Backup directory escapes APP_DATA_ROOT.');
  }

  try {
    const stats = fs.lstatSync(backupDir);
    if (stats.isSymbolicLink()) {
      throw new StorageError('Backup directory is a symbolic link. Refusing to use it.');
    }
    if (!stats.isDirectory()) {
      throw new StorageError('Backup directory path exists but is not a directory.');
    }
  } catch (err) {
    if (err instanceof StorageError) throw err;
    if (err.code === 'ENOENT') {
      fs.mkdirSync(backupDir, { recursive: true, mode: 0o700 });
      return backupDir;
    }
    throw new StorageError('Cannot access backup directory.');
  }

  return backupDir;
}

/**
 * Resolve a backup filename to an absolute path strictly within the managed
 * backup directory. Rejects traversal, absolute-path inputs, non-managed
 * filename shapes, and symlinked components.
 *
 * @param {string} backupDir - Resolved, existing backup directory
 * @param {string} filename - Application-managed backup filename
 * @returns {string} Resolved absolute path
 * @throws {StorageError}
 */
export function resolveBackupFile(backupDir, filename) {
  if (!filename || typeof filename !== 'string') {
    throw new StorageError('Backup filename must be a non-empty string.');
  }
  if (path.isAbsolute(filename) || filename.includes('/') || filename.includes('\\')) {
    throw new StorageError('Backup filename must not contain path separators.');
  }
  if (!isManagedBackupFilename(filename)) {
    throw new StorageError('Backup filename does not match the managed backup naming contract.');
  }

  const normalizedRoot = path.resolve(backupDir);
  const resolved = path.resolve(normalizedRoot, filename);

  if (!isContained(normalizedRoot, resolved)) {
    throw new StorageError('Backup path escapes the managed backup directory.');
  }

  checkSymlinks(normalizedRoot, resolved);

  return resolved;
}

export { BACKUP_PREFIX, BACKUP_EXT };
